### ISSUE TITLE
tcp_ep send failed:input/output error

### ISSUE THREAD

**Issue by LiuYinfeng01** [ai-dynamo/dynamo#418]
My device is H20, and my install conmand is 
```
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install -yq python3-dev python3-pip python3-venv libucx0
python3 -m venv venv
source venv/bin/activate

pip install ai-dynamo[all]
apt-get purge libucx0
```
and I get segment error when run P/D disaggregation .
 refer to #285 .
So I try to pip uninstall nixl and install nixl from source. My conmand is 
```
sudo apt install build-essential cmake pkg-config
wget https://github.com/openucx/ucx/releases/download/v1.18.0/ucx-1.18.0.tar.gz
tar xzf ucx-1.18.0.tar.gz
cd ucx-1.18.0
./contrib/configure-release --prefix=<PATH_TO_INSTALL>/install
make -j8
make install

cd install
export PKG_CONFIG_PATH=$PWD/lib/pkgconfig:$PKG_CONFIG_PATH

sudo apt install -y cuda-toolkit-12-5
export C_INCLUDE_PATH=/usr/local/cuda-12.5/targets/x86_64-linux/include:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=/usr/local/cuda-12.5/targets/x86_64-linux/include:$CPLUS_INCLUDE_PATH
export LD_LIBRARY_PATH=/usr/local/cuda-12.5/targets/x86_64-linux/lib:$LD_LIBRARY_PATH 

meson setup <name_of_build_dir>
cd <name_of_build_dir>
ninja
ninja-install
```

and test the nixl ut test, the test return successfully.
`python nixl/test/python/nixl_api_test.py`

but when I run pd disaggregation, it shows errors as belows.

```
dynamo/examples/llm# dynamo serve graphs.disagg:Frontend -f ./configs/disagg.yaml
2025-03-26T10:37:48+0000 [WARNING] [cli] Converting 'Frontend' to lowercase: 'frontend'.
INFO 03-26 10:37:51 __init__.py:190] Automatically detected platform cuda.
INFO 03-26 10:37:51 nixl.py:16] NIXL is available
2025-03-26T10:37:52+0000 [WARNING] [cli] Converting 'Frontend' to lowercase: 'frontend'.
2025-03-26T10:37:53+0000 [INFO] [cli] Starting graphs.disagg:Frontend (Press CTRL+C to quit)
INFO 03-26 10:37:57 __init__.py:190] Automatically detected platform cuda.
INFO 03-26 10:37:57 __init__.py:190] Automatically detected platform cuda.
INFO 03-26 10:37:57 __init__.py:190] Automatically detected platform cuda.
INFO 03-26 10:37:57 __init__.py:190] Automatically detected platform cuda.
INFO 03-26 10:37:58 nixl.py:16] NIXL is available
INFO 03-26 10:37:58 nixl.py:16] NIXL is available
INFO 03-26 10:37:58 nixl.py:16] NIXL is available
INFO 03-26 10:37:58 nixl.py:16] NIXL is available
Using default Dynamo address: dynamo/PrefillWorker
Chunked prefill is not supported yet, setting to False
Async output processing is not supported yet, setting to True
Prefill must be done eagerly, setting to True
Using default Dynamo address: dynamo/Processor
Using default Dynamo address: dynamo/VllmWorker
Chunked prefill is not supported yet, setting to False
Preemption mode is not supported yet, setting to swap
chat model deepseek-ai/DeepSeek-R1-Distill-Llama-8B removed from the public namespace: public
2025-03-26T10:37:59.790850Z  INFO dynamo_llm::http::service::discovery: removed Chat model: deepseek-ai/DeepSeek-R1-Distill-Llama-8B
Added new chat model deepseek-ai/DeepSeek-R1-Distill-Llama-8B
+------------+------------------------------------------+-----------+-----------+------------------+
| MODEL TYPE | MODEL NAME                               | NAMESPACE | COMPONENT | ENDPOINT         |
+------------+------------------------------------------+-----------+-----------+------------------+
| chat       | deepseek-ai/DeepSeek-R1-Distill-Llama-8B | dynamo    | Processor | chat/completions |
+------------+------------------------------------------+-----------+-----------+------------------+
2025-03-26T10:38:00.422105Z  INFO dynamo_llm::http::service::discovery: added Chat model: deepseek-ai/DeepSeek-R1-Distill-Llama-8B
Starting HTTP server
2025-03-26T10:38:01.048768Z  INFO dynamo_runtime::pipeline::network::tcp::server: tcp transport service on 10.67.225.211:45097
2025-03-26T10:38:01.049191Z  INFO dynamo_llm::http::service::service_v2: Starting HTTP service on: 0.0.0.0:8000 address="0.0.0.0:8000"

thread 'tokio-runtime-worker' panicked at /workspace/lib/llm/src/http/service/service_v2.rs:69:33:
could not bind to address: 0.0.0.0:8000
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2025-03-26T10:38:01.049239Z  INFO dynamo_llm::http::service::discovery: added Chat model: deepseek-ai/DeepSeek-R1-Distill-Llama-8B
Error: task 20 panicked with message "could not bind to address: 0.0.0.0:8000"
2025-03-26T10:38:01+0000 [INFO] [entry_service:Frontend:1] Service Frontend initialized
INFO 03-26 10:38:02 __init__.py:190] Automatically detected platform cuda.
INFO 03-26 10:38:02 __init__.py:190] Automatically detected platform cuda.
INFO 03-26 10:38:02 nixl.py:16] NIXL is available
INFO 03-26 10:38:03 nixl.py:16] NIXL is available
Using default Dynamo address: dynamo/VllmWorker
[Processor] comp_ns: dynamo, comp_name: VllmWorker
Waiting for workers to be ready.
 Current: 0, Required: 1
Waiting for workers to be ready.
 Current: 0, Required: 1
INFO 03-26 10:38:12 config.py:542] This model supports multiple tasks: {'classify', 'embed', 'generate', 'score', 'reward'}. Defaulting to 'generate'.
INFO 03-26 10:38:12 llm_engine.py:246] Initializing a V0 LLM engine (v0.7.2) with config: model='deepseek-ai/DeepSeek-R1-Distill-Llama-8B', speculative_config=None, tokenizer='deepseek-ai/DeepSeek-R1-Distill-Llama-8B', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=16384, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=deepseek-ai/DeepSeek-R1-Distill-Llama-8B, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=False, chunked_prefill_enabled=False, use_async_output_proc=True, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"max_capture_size":256}, use_cached_outputs=True,
INFO 03-26 10:38:12 config.py:542] This model supports multiple tasks: {'reward', 'generate', 'embed', 'score', 'classify'}. Defaulting to 'generate'.
INFO 03-26 10:38:12 llm_engine.py:246] Initializing a V0 LLM engine (v0.7.2) with config: model='deepseek-ai/DeepSeek-R1-Distill-Llama-8B', speculative_config=None, tokenizer='deepseek-ai/DeepSeek-R1-Distill-Llama-8B', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=16384, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=deepseek-ai/DeepSeek-R1-Distill-Llama-8B, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=False, chunked_prefill_enabled=False, use_async_output_proc=False, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[],"max_capture_size":0}, use_cached_outputs=True,
Waiting for workers to be ready.
 Current: 0, Required: 1
INFO 03-26 10:38:13 cuda.py:230] Using Flash Attention backend.
INFO 03-26 10:38:14 cuda.py:230] Using Flash Attention backend.
Waiting for workers to be ready.
 Current: 0, Required: 1
INFO 03-26 10:38:15 model_runner.py:1110] Starting to load model deepseek-ai/DeepSeek-R1-Distill-Llama-8B...
INFO 03-26 10:38:15 model_runner.py:1110] Starting to load model deepseek-ai/DeepSeek-R1-Distill-Llama-8B...
INFO 03-26 10:38:16 weight_utils.py:252] Using model weights format ['*.safetensors']
INFO 03-26 10:38:16 weight_utils.py:252] Using model weights format ['*.safetensors']
Loading safetensors checkpoint shards:   0% Completed | 0/2 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:   0% Completed | 0/2 [00:00<?, ?it/s]
Waiting for workers to be ready.
 Current: 0, Required: 1
Loading safetensors checkpoint shards:  50% Completed | 1/2 [00:01<00:01,  1.25s/it]
Loading safetensors checkpoint shards:  50% Completed | 1/2 [00:01<00:01,  1.21s/it]
Waiting for workers to be ready.
 Current: 0, Required: 1
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:02<00:00,  1.50s/it]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:02<00:00,  1.46s/it]

INFO 03-26 10:38:20 model_runner.py:1115] Loading model weights took 14.9888 GB
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:02<00:00,  1.48s/it]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:02<00:00,  1.44s/it]

INFO 03-26 10:38:20 model_runner.py:1115] Loading model weights took 14.9888 GB
Waiting for workers to be ready.
 Current: 0, Required: 1
INFO 03-26 10:38:22 worker.py:269] Memory profiling takes 2.06 seconds
INFO 03-26 10:38:22 worker.py:269] the current vLLM instance can use total_gpu_memory (95.11GiB) x gpu_memory_utilization (0.90) = 85.60GiB
INFO 03-26 10:38:22 worker.py:269] model weights take 14.99GiB; non_torch_memory takes 0.12GiB; PyTorch activation peak memory takes 1.72GiB; the rest of the memory reserved for KV Cache is 68.77GiB.
INFO 03-26 10:38:22 executor_base.py:110] # CUDA blocks: 35210, # CPU blocks: 2048
INFO 03-26 10:38:22 executor_base.py:115] Maximum concurrency for 16384 tokens per request: 34.38x
INFO 03-26 10:38:22 worker.py:269] Memory profiling takes 2.09 seconds
INFO 03-26 10:38:22 worker.py:269] the current vLLM instance can use total_gpu_memory (95.11GiB) x gpu_memory_utilization (0.90) = 85.60GiB
INFO 03-26 10:38:22 worker.py:269] model weights take 14.99GiB; non_torch_memory takes 0.12GiB; PyTorch activation peak memory takes 1.72GiB; the rest of the memory reserved for KV Cache is 68.77GiB.
INFO 03-26 10:38:22 executor_base.py:110] # CUDA blocks: 35210, # CPU blocks: 2048
INFO 03-26 10:38:22 executor_base.py:115] Maximum concurrency for 16384 tokens per request: 34.38x
Waiting for workers to be ready.
 Current: 0, Required: 1
INFO 03-26 10:38:23 model_runner.py:1434] Capturing cudagraphs for decoding. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI. If out-of-memory error occurs during cudagraph capture, consider decreasing `gpu_memory_utilization` or switching to eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
Capturing CUDA graph shapes:   3%|█▋                                                           | 1/35 [00:00<00:13,  2.50it/s]INFO 03-26 10:38:24 llm_engine.py:477] init engine (profile, create kv cache, warmup model) took 3.69 seconds
Capturing CUDA graph shapes:   6%|███▍                                                         | 2/35 [00:00<00:12,  2.68it/s]INFO 03-26 10:38:24 nixl.py:38] Initializing NIXL wrapper
[1742985504.589702] [dl-server-h20:7722 :0]     ucp_context.c:2137 UCX  WARN  UCP API version is incompatible: required >= 1.18, actual 1.16.0 (loaded from /lib/x86_64-linux-gnu/libucp.so.0)
Initialized NIXL agent: 451b1784-cb8e-4cb1-be6c-ff132a59aa04
Capturing CUDA graph shapes:   9%|█████▏                                                       | 3/35 [00:01<00:10,  2.93it/s]PrefillWorker initialized
[DEBUG] prefill queue handler entered
Prefill queue: nats://localhost:4222:vllm
prefill queue handler started
Capturing CUDA graph shapes:  14%|████████▋                                                    | 5/35 [00:01<00:09,  3.24it/s]Waiting for workers to be ready.
 Current: 0, Required: 1
Capturing CUDA graph shapes:  26%|███████████████▋                                             | 9/35 [00:03<00:10,  2.41it/s]Waiting for workers to be ready.
 Current: 0, Required: 1
Capturing CUDA graph shapes:  40%|████████████████████████                                    | 14/35 [00:05<00:09,  2.22it/s]Waiting for workers to be ready.
 Current: 0, Required: 1
Capturing CUDA graph shapes:  51%|██████████████████████████████▊                             | 18/35 [00:07<00:07,  2.29it/s]Waiting for workers to be ready.
 Current: 0, Required: 1
Capturing CUDA graph shapes:  66%|███████████████████████████████████████▍                    | 23/35 [00:09<00:05,  2.35it/s]Waiting for workers to be ready.
 Current: 0, Required: 1
Capturing CUDA graph shapes:  80%|████████████████████████████████████████████████            | 28/35 [00:11<00:02,  2.44it/s]Waiting for workers to be ready.
 Current: 0, Required: 1
Capturing CUDA graph shapes:  94%|████████████████████████████████████████████████████████▌   | 33/35 [00:13<00:00,  2.47it/s]Waiting for workers to be ready.
 Current: 0, Required: 1
Capturing CUDA graph shapes: 100%|████████████████████████████████████████████████████████████| 35/35 [00:14<00:00,  2.41it/s]
INFO 03-26 10:38:38 model_runner.py:1562] Graph capturing finished in 15 secs, took 0.32 GiB
INFO 03-26 10:38:38 llm_engine.py:477] init engine (profile, create kv cache, warmup model) took 18.23 seconds
INFO 03-26 10:38:38 nixl.py:38] Initializing NIXL wrapper
[1742985518.743062] [dl-server-h20:7760 :0]     ucp_context.c:2137 UCX  WARN  UCP API version is incompatible: required >= 1.18, actual 1.16.0 (loaded from /lib/x86_64-linux-gnu/libucp.so.0)
Initialized NIXL agent: 7024278a-75a9-41e2-9b33-db882cc29bfa
VllmWorker has been initialized
2025-03-26T10:38:39.542582Z ERROR dynamo_runtime::transports::etcd: kv watcher error forwarding WatchEvent::Put: channel closed
2025-03-26T10:38:39.542608Z ERROR dynamo_runtime::transports::etcd: kv watcher error forwarding WatchEvent::Put: channel closed
Prefilling remotely for request 76b0a27c-0d3d-44a6-959b-da1ff87257dc with length 193
INFO 03-26 10:41:29 engine.py:404] Added request 76b0a27c-0d3d-44a6-959b-da1ff87257dc.
Dequeued prefill request: 76b0a27c-0d3d-44a6-959b-da1ff87257dc
Loaded nixl metadata from engine 721887f4-4d55-46a1-b65c-c56ca1cefd86 into engine 44c4d83e-dd30-4454-8485-10ff8b788932
INFO 03-26 10:41:34 metrics.py:455] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 38.6 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%.
INFO 03-26 10:41:34 engine.py:404] Added request 76b0a27c-0d3d-44a6-959b-da1ff87257dc.
[1742985695.403339] [dl-server-h20:7722 :0]          tcp_ep.c:1175 UCX  ERROR tcp_ep 0x540dba70 (state=CONNECTED): send(140) failed: Input/output error
error handling callback was invoked with status -25 (Connection reset by remote peer)
prefill queue handler created
ERROR 03-26 10:41:35 engine.py:244] nixlBackendError('NIXL_ERR_BACKEND')
ERROR 03-26 10:41:35 engine.py:244] Traceback (most recent call last):
ERROR 03-26 10:41:35 engine.py:244]   File "/home/ubuntu/venv/lib/python3.12/site-packages/vllm/engine/multiprocessing/engine.py", line 242, in start
ERROR 03-26 10:41:35 engine.py:244]     self.run_engine_loop()
ERROR 03-26 10:41:35 engine.py:244]   File "/home/ubuntu/venv/lib/python3.12/site-packages/vllm/engine/multiprocessing/engine.py", line 315, in run_engine_loop
ERROR 03-26 10:41:35 engine.py:244]     request_outputs = self.engine_step()
ERROR 03-26 10:41:35 engine.py:244]                       ^^^^^^^^^^^^^^^^^^
ERROR 03-26 10:41:35 engine.py:244]   File "/home/ubuntu/venv/lib/python3.12/site-packages/vllm/engine/multiprocessing/engine.py", line 333, in engine_step
ERROR 03-26 10:41:35 engine.py:244]     raise e
ERROR 03-26 10:41:35 engine.py:244]   File "/home/ubuntu/venv/lib/python3.12/site-packages/vllm/engine/multiprocessing/engine.py", line 324, in engine_step
ERROR 03-26 10:41:35 engine.py:244]     return self.engine.step()
ERROR 03-26 10:41:35 engine.py:244]            ^^^^^^^^^^^^^^^^^^
ERROR 03-26 10:41:35 engine.py:244]   File "/home/ubuntu/venv/lib/python3.12/site-packages/vllm/engine/llm_engine.py", line 1505, in step
ERROR 03-26 10:41:35 engine.py:244]     outputs, request_notif_counter, request_done_counter = self.model_executor.execute_model(
ERROR 03-26 10:41:35 engine.py:244]                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 03-26 10:41:35 engine.py:244]   File "/home/ubuntu/venv/lib/python3.12/site-packages/vllm/executor/executor_base.py", line 138, in execute_model
ERROR 03-26 10:41:35 engine.py:244]     output = self.collective_rpc("execute_model",
ERROR 03-26 10:41:35 engine.py:244]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 03-26 10:41:35 engine.py:244]   File "/home/ubuntu/venv/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 51, in collective_rpc
ERROR 03-26 10:41:35 engine.py:244]     answer = run_method(self.driver_worker, method, args, kwargs)
ERROR 03-26 10:41:35 engine.py:244]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 03-26 10:41:35 engine.py:244]   File "/home/ubuntu/venv/lib/python3.12/site-packages/vllm/utils.py", line 2220, in run_method
ERROR 03-26 10:41:35 engine.py:244]     return func(*args, **kwargs)
ERROR 03-26 10:41:35 engine.py:244]            ^^^^^^^^^^^^^^^^^^^^^
ERROR 03-26 10:41:35 engine.py:244]   File "/home/ubuntu/venv/lib/python3.12/site-packages/vllm/worker/worker_base.py", line 462, in execute_model
ERROR 03-26 10:41:35 engine.py:244]     self._transfer_blocks(worker_input)
ERROR 03-26 10:41:35 engine.py:244]   File "/home/ubuntu/venv/lib/python3.12/site-packages/vllm/worker/worker.py", line 345, in _transfer_blocks
ERROR 03-26 10:41:35 engine.py:244]     self.nixl_connector.transfer_mem(src_block_ids, staging_block_ids, dst_block_ids, dst_engine_id, notify_msg)
ERROR 03-26 10:41:35 engine.py:244]   File "/home/ubuntu/venv/lib/python3.12/site-packages/vllm/distributed/device_communicators/nixl.py", line 241, in transfer_mem
ERROR 03-26 10:41:35 engine.py:244]     self._transfer_mem_create_xfer(src_block_ids, staging_block_ids, dst_block_ids, dst_engine_id, notify_msg)
ERROR 03-26 10:41:35 engine.py:244]   File "/home/ubuntu/venv/lib/python3.12/site-packages/vllm/distributed/device_communicators/nixl.py", line 330, in _transfer_mem_create_xfer
ERROR 03-26 10:41:35 engine.py:244]     status = self.nixl_wrapper.transfer(handle)
ERROR 03-26 10:41:35 engine.py:244]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 03-26 10:41:35 engine.py:244]   File "/opt/nvidia/nvda_nixl/lib/python3/dist-packages/nixl/_api.py", line 316, in transfer
ERROR 03-26 10:41:35 engine.py:244]     status = self.agent.postXferReq(handle, notif_msg)
ERROR 03-26 10:41:35 engine.py:244]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 03-26 10:41:35 engine.py:244] nixl._bindings.nixlBackendError: NIXL_ERR_BACKEND
[1742985695.835352] [dl-server-h20:7722 :0]           flush.c:57   UCX  ERROR req 0x54bc0bc0: error during flush: Connection reset by remote peer
[rank0]:[W326 10:41:36.360634040 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
INFO 03-26 10:41:39 metrics.py:455] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%.
^C2025-03-26T10:45:36+0000 [INFO] [entry_service:Frontend:1] Service instance cleanup finalized
```

**Comment by dmitry-tokarev-nv** [comment]
Possibly related to #285 and #350

**Comment by jokerwyt** [comment]
Got the same error

**Comment by dzier** [comment]
Looks like the issue has been resolved in #285 and #350. Closing the issue. Please re-open if bug persists.
